### ISSUE TITLE
vertical mis-alignment of timestamps under avatar

### ISSUE THREAD

**Issue by ge0rg** [jabbercat/jabbercat#64]
When a person with an avatar image writes multiple messages, the timestamps are not vertically aligned. Example picture attached.

![image](https://user-images.githubusercontent.com/165635/37087398-70870ca0-21fa-11e8-954a-c34472b69caf.png)

**Comment by horazont** [comment]
(That’s a confusing way to censor a screenshot.)

This is a side-effect of fixing a few other issues. I don’t know for sure how to express this properly in HTML+CSS unfortunately.

**Comment by ge0rg** [comment]
So now you fixed the vertical alignment of the timestamp, but broke the vertical alignment of the text to the right, for the first message...

![image](https://user-images.githubusercontent.com/165635/37288673-2f08d828-2608-11e8-86ea-2cdac0a9fbb5.png)

Also, the long timestamp is US date with AM/PM, while the short ones are 24hr?

**Comment by horazont** [comment]
That alignment never worked and I don’t intend to fix that one. The reason is that we want to show a full date on the first message (albeit we could replace that by a full-width date marker outside of the message block at some point). Indenting all messages in the block due to that full timestamp seems like a huge amount of space wasted.

Regarding the timestamp, welcome to the funny world of localization with JavaScript! Make a separate issue for that, I think we’ll end up providing fully localized parts to the JS stuff.
