### ISSUE TITLE
Re-design the roster workflow

### ISSUE THREAD

**Issue by horazont** [jabbercat/jabbercat#83]
On the one hand, we want to save space by having the roster disappear automatically. On the other hand, the roster disappearance is (a) buggy and (b) confusing to users.

We need a better way.

**Comment by sebastianriese** [comment]
To list one of the (perceived) bugs: I am really annoyed, that I have to manually remove the content from the search bar, to make the roster vanish if there was still more than one match, my conclusion from this is:
* Text in the non-focussed search bar should not keep the roster visible, Ctrl-l is already doing the right thing and marking all text in the search bar (so that simply typing the new search will delete the old text).

**Comment by horazont** [comment]
### Requirements

* Items must not change order based on remote events by default.
* Ongoing conversations must be grouped somewhere so that they can be visible on a single page at the same time (if they fit on a single page generally).
* There should be a clear visual distinction between an ongoing conversation and a rather inactive roster item.
* There should be a way to show a presence indicator.
* Avatars
* Tags

### Solution 1: Merge Conversation and Roster List

A similar thing was suggested in #14.

- Conversations can be grouped to the top with a sorting function.
- How to solve the "item jumps to the top when I get a message" issue? → Duplicate active roster items to the top.
- Draw a clear separator between active conversations and the remainder of the roster
- During search, don’t show active conversations? (To avoid displaying duplicates)
- Display roster items differently from normal conversation items
- Offer config option to hide roster when not searching

### Any other suggestions?

**Comment by horazont** [comment]
I’m very happy with the new design. There may be some minor issues left, but I think we can go into this direction further. If you disagree, feel free to comment here (and re-open).
