### ISSUE TITLE
Update the website and github for XMPP

### ISSUE THREAD

**Issue by Neustradamus** [jabbercat/jabbercat#89]
I see the Jabber network etc but it is the XMPP network...

https://github.com/jabbercat/jabbercat
"Qt-based Instant Messaging client for the Jabber (XMPP) network" -> the XMPP network
"The Jabber® client of the future!" -> it is an XMPP client

https://jabbercat.org/
"JabberCat is an instant messenger which uses the long-established Jabber network (based on XMPP)." -> the XMPP network

"Join our Jabber group chat: jabbercat@conference.zombofant.net" -> XMPP muc room
"Contact the lead developer via Jabber" -> via XMPP, Jabber ID:

https://jabbercat.org/testing/index.html
"directly send Jabber IMs to jonas@wielicki.name (adding them to the roster before sending a message is recommended; there are some anti-spam measures in place which may catch you otherwise.)." -> Jabber IMs -> on XMPP

**Comment by sebastianriese** [comment]
This is deliberate and no accident. Some people (including the JabberCat team) think that we should begin to term the service Jabber which is built on top of the protocol XMPP.  This is analogous to the way the Web is built atop HTTP or E-Mail is built atop SMTP and POP3 or IMAP. The term Jabber exists, is well known and is already used in this way (partly due to legacy) and has the advantage of being much easier to pronounce than XMPP.

**Comment by horazont** [comment]
See also https://wiki.xmpp.org/web/Usability/Glossary
